apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/asheeque/kubedemo.git
    targetRevision: main
    path: dev
  destination:
    server: https://kubernetes.default.svc
