apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworldpod
  template:
    metadata:
      labels:
        app: helloworldpod
    spec:
      containers:
      - name: helloworldapp
        image: dockercloud/hello-world:latest
        ports:
        - containerPort: 3000
        env:
        - name: LISTEN_PORT
          value: "3000"
